site_name: Bases de datos con C#

docs_dir: 'md'

site_dir: 'docs'

theme:
  name: material

  font:
    text: Poppins
    code: JetBrains Mono

  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    #- content.action.print

  palette:

    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambiar a oscuro

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a claro

plugins:
  - search
#  - with-pdf
  - page-to-pdf
  - print-site

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Inicio: index.md
  - SQLite: conexion.md
  - Instalar SQLite: instalar.md
  - Ejecutar SQL: flujo.md
  - Ejemplo: ejemplo.md
  - About: about.md